<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_bot">
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="front_lidar_arm">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="front_lidar_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo>
        <plugin name="diff_drive_control" filename="libgazebo_ros_diff_drive.so">      
            <!-- Update rate in Hz -->
            <update_rate>50</update_rate>
      
            <!-- wheels -->
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
      
            <!-- kinematics -->
            <wheel_separation>${base_width + wheel_length}</wheel_separation>
            <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      
            <!-- limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
      
            <!-- input -->
            <command_topic>cmd_vel</command_topic>
      
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
      
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
      
          </plugin>
    </gazebo>
</robot>