<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_bot">
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="front_lidar_arm">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="front_lidar_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo>
        <plugin name="diff_drive_control" filename="libgazebo_ros_diff_drive.so">      
            <!-- Update rate in Hz -->
            <update_rate>50</update_rate>
      
            <!-- wheels -->
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
      
            <!-- kinematics -->
            <wheel_separation>${base_width + wheel_length}</wheel_separation>
            <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      
            <!-- limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
      
            <!-- input -->
            <command_topic>cmd_vel</command_topic>
      
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
      
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
      
          </plugin>
    </gazebo>

    <gazebo reference="front_lidar_link">
        <sensor name="lidar" type="ray">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
              <scan>
                <vertical>
                  <samples>1</samples>
                  <resolution>1.000000</resolution>
                  <min_angle>-1.570000</min_angle>
                  <max_angle>-1.570001</max_angle>
                </vertical>
              </scan>
              <range>
                <min>0.010000</min>
                <max>5</max>
                <resolution>0.015000</resolution>
              </range>
              <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
              </noise>
            </ray>
            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
              <ros>
                <remapping>~/out:=range</remapping>
              </ros>
              <output_type>sensor_msgs/Range</output_type>
              <frame_name>lidar_link</frame_name>
            </plugin>
          </sensor>
    </gazebo>
</robot>