<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_bot">
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}" />
            <inertia ixy="0.0" ixz="0.0" iyz="0.0" ixx="${m / 12.0 * (h*h + d*d)}" iyy="${m / 12.0 * (w*w + d*d)}" izz="${m / 12.0 * (w*w + h*h)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixy="0.0" ixz="0.0" iyz="0.0" ixx="${m / 12.0 * (3.0*r*r + h*h)}" iyy="${m / 12.0 * (3.0*r*r + h*h)}" izz="${m / 2.0 * r*r}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixy="0.0" ixz="0.0" iyz="0.0" ixx="${m * 2.0 / 5.0 * r*r}" iyy="${m * 2.0 / 5.0 * r*r}" izz="${m * 2.0 / 5.0 * r*r}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel" params="prefix side">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" />
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${prefix}_wheel" />
            <origin xyz="${drive_wheel_offset} ${(base_width / 2 * side)} 0" rpy="0 0 0" />
        </joint>
    </xacro:macro>
</robot>