<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_bot">
    <!-- <xacro:include filename="macros.xacro" />
    <xacro:include filename="properties.xacro" /> -->

    <link name="front_lidar_arm">
        <xacro:box_inertia m="0.1" w="${front_lidar_arm_length}" h="0.02" d="0.02" />
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${front_lidar_arm_length} 0.02 0.02" />
            </geometry>
            <!-- <material name="blue" /> -->
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${front_lidar_arm_length} 0.02 0.02" />
            </geometry>
        </collision>
    </link>

    <link name="front_lidar_link">
        <xacro:box_inertia m="0.1" w="${front_lidar_size}" h="${front_lidar_size}" d="${front_lidar_size}" />
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${front_lidar_size} ${front_lidar_size} ${front_lidar_size}" />
            </geometry>
            <!-- <material name="blue" /> -->
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${front_lidar_size} ${front_lidar_size} ${front_lidar_size}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="front_lidar_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="front_lidar_arm" />
        <origin xyz="${base_length/2 + front_lidar_arm_length/2} 0 0" rpy="0 0 0" />
    </joint>

    <joint name="front_lidar_joint" type="fixed">
        <parent link="front_lidar_arm" />
        <child link="front_lidar_link" />
        <origin xyz="${front_lidar_arm_length/2 - 0.01} 0 -0.01" rpy="0 0 0" />
    </joint>
</robot>